### ISSUE TITLE
TypeError: Cannot read property 'getServices' of undefined?

### ISSUE THREAD

**Issue by AnderssonPeter** [Spartan-II-117/node-red-contrib-home-assistant-llat#44]
**Describe the bug**
When opening a ha node i get `TypeError: Cannot read property 'getServices' of undefined` error.

**To Reproduce**
* Add a call service node
* Add server
* Save
* Open node again
* Error dialog is shown

**Expected behavior**
I should not see the error, and get auto completion.

**Environment (please complete the following information):**
 - Node Red Version: 0.19.4
 - NR Home Assistant Plugin Version: 0.3.10
 - Home Assistant Version: 0.80.1
 - Is Node Red running in Docker: yes

**Additional context**
```bash
TypeError: Cannot read property 'getServices' of undefined,
    at ConfigServerNode.getServices (/data/node_modules/node-red-contrib-home-assistant-llat/nodes/config-server/config-server.js:18:39),
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5),
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13),
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3),
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5),
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22,
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12),
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10),
    at /usr/src/node-red/node_modules/express/lib/application.js:233:9,
    at /usr/src/node-red/node_modules/express/lib/router/index.js:635:15,
```

**Comment by Spartan-II-117** [comment]
does this persist after a restart of node-red or a deploy?

**Comment by AnderssonPeter** [comment]
I have tried both and yes it presists.

And im using the following docker-compose
```yaml
  node-red:
    image:  nodered/node-red-docker:v8
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - ./node-red/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "homeassistant:192.168.94.55"
```
